highlighter: rouge
markdown: kramdown
kramdown:
  entity_output: symbol
permalink: none
destination: site
exclude: ['README.md','content', 'LICENSE', 'merge_pr.py']
keep_files: ['docs']
url: https://spark.apache.org
